# ======================================================================
#  Jupyter-Book configuratie
#  Plaats dit bestand in de project-root (zelfde niveau als _toc.yml)
# ======================================================================

title: InfoVisA4
author: Mark Kuster

# --------------------------------------------------
# 1. Notebooks altijd opnieuw uitvoeren bij build
execute:
  execute_notebooks: force

# --------------------------------------------------
# 2. Repo-info (past de knoppen + Binder-url aan)
repository:
  url: https://github.com/Mark-Kuster-UvA/InfoVisA4
  branch: main
  path_to_book: ""

# --------------------------------------------------
# 3. HTML-opties
html:
  use_issues_button: true
  use_repository_button: true

# --------------------------------------------------
# 4. Launch-knoppen + Thebe (voor ipywidgets)
launch_buttons:
  binderhub_url: https://mybinder.org
  thebe: true
  colab_url: ""
  jupyterhub_url: ""

# --------------------------------------------------
# 5. Extra sphinx-instellingen (plotly / require.js)
sphinx:
  extra_extensions:
    - IPython.sphinxext.ipython_console_highlighting
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js